# Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
# See AUTHORS.txt
# All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of Dynawo, an hybrid C++/Modelica open source time domain simulation tool for power systems.
FROM centos:6.6
LABEL maintainer Gautier Bureau "gautier.bureau@rte-france.com"

ENV USER "dynawo_user"

RUN yum upgrade -y \
&& yum update -y \
&& yum install -y \
  git \
  gcc \
  gcc-c++ \
  gcc-gfortran \
  autoconf \
  automake \
  make \
  sudo \
  libtool \
  cmake \
  hwloc \
  java-1.8.0-openjdk \
  blas-devel \
  lapack-devel \
  expat-devel \
  glibc-devel \
  xulrunner-devel \
  sqlite-devel \
  doxygen \
  qt-devel \
  gettext \
  patch \
  wget \
  python-devel \
  ncurses-devel \
  readline-devel \
  unzip \
  vim \
  tar \
  xz \
  python-lxml \
  libcurl-devel \
  curl \
  flex \
  bison \
  chrpath \
  epel-release

RUN yum install -y python-pip python-psutil dpkg gtest-devel gmock-devel bash-completion

ENV BOOST_VERSION 1_64_0

RUN cd /tmp \
&& wget https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION//_/.}/boost_${BOOST_VERSION}.tar.gz \
&& tar -xzvf boost_${BOOST_VERSION}.tar.gz \
&& cd boost_${BOOST_VERSION} \
&& ./bootstrap.sh --prefix=/opt/boost --without-icu --with-libraries=filesystem,program_options,serialization,system,log,iostreams,atomic \
&& ./b2 -s NO_BZIP2=1 --disable-icu boost.locale.icu=off cxxflags="-fPIC" link=static variant=release install \
&& rm -f /tmp/boost_${BOOST_VERSION}.tar.gz \
&& cd ~ \
&& rm -rf /tmp/boost_${BOOST_VERSION}*

ENV ZLIB_VERSION 1.2.11

RUN cd /tmp \
&& wget https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz \
&& tar xzf zlib-${ZLIB_VERSION}.tar.gz \
&& cd zlib-${ZLIB_VERSION} \
&& CFLAGS="-fPIC" ./configure --static --prefix=/opt/zlib \
&& make \
&& make install \
&& rm -f /tmp/zlib-${ZLIB_VERSION}.tar.gz \
&& cd ~ \
&& rm -rf /tmp/zlib-${ZLIB_VERSION}*

ENV LCOV_VERSION 1.13

RUN cd /tmp \
&& wget https://downloads.sourceforge.net/ltp/lcov-${LCOV_VERSION}.tar.gz \
&& tar -xzvf lcov-${LCOV_VERSION}.tar.gz \
&& cd lcov-${LCOV_VERSION} \
&& make install \
&& rm -f /tmp/lcov-${LCOV_VERSION}.tar.gz \
&& cd ~ \
&& rm -rf /tmp/lcov-${LCOV_VERSION}*

ENV CMAKE_VERSION 3.9.6
ENV CMAKE_VERSION_SHORT 3.9

RUN cd /tmp \
&& wget https://cmake.org/files/v${CMAKE_VERSION_SHORT}/cmake-${CMAKE_VERSION}.tar.gz \
&& tar xzf cmake-${CMAKE_VERSION}.tar.gz \
&& cd cmake-${CMAKE_VERSION} \
&& ./bootstrap \
&& make \
&& make install \
&& rm -f /tmp/cmake-${CMAKE_VERSION}.tar.gz  \
&& cd ~ \
&& rm -rf /tmp/cmake-${CMAKE_VERSION}*

ENV LIBARCHIVE_VERSION 3.3.3

RUN cd /tmp \
&& wget https://libarchive.org/downloads/libarchive-${LIBARCHIVE_VERSION}.tar.gz \
&& tar xzf libarchive-${LIBARCHIVE_VERSION}.tar.gz \
&& cd libarchive-${LIBARCHIVE_VERSION} \
&& mkdir build-cmake \
&& cd build-cmake \
&& CFLAGS="-fPIC" cmake .. -DCMAKE_INSTALL_PREFIX=/opt/libarchive -DCMAKE_BUILD_TYPE=Release -DENABLE_BZip2=OFF -DENABLE_LZ4=OFF -DENABLE_LZMA=OFF -DENABLE_NETTLE=OFF -DENABLE_OPENSSL=OFF -DENABLE_EXPAT=OFF -DCMAKE_PREFIX_PATH=/opt/zlib \
&& make \
&& make install \
&& rm -f /opt/libarchive/lib/*.so* \
&& rm -f /tmp/libarchive-${LIBARCHIVE_VERSION}.tar.gz \
&& cd ~ \
&& rm -rf /tmp/libarchive-${LIBARCHIVE_VERSION}*

RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
  && chmod +x /usr/local/bin/gosu

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN useradd -l -m -d /home/${USER} --user-group ${USER}

WORKDIR /home/${USER}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
