# Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
# See AUTHORS.txt
# All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of Dynawo, an hybrid C++/Modelica open source time domain simulation tool for power systems.
FROM ubuntu:19.04
LABEL maintainer Gautier Bureau "gautier.bureau@rte-france.com"

ENV USER "dynawo_user"

ENV TZ=Europe/Paris \
DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
&& apt-get upgrade -y -q \
&& apt-get install -y git \
  gcc \
  g++ \
  gfortran \
  autoconf \
  pkgconf \
  automake \
  make \
  sudo \
  libtool \
  cmake \
  hwloc \
  openjdk-11-jdk \
  libblas-dev \
  liblpsolve55-dev \
  libarchive-dev \
  doxygen \
  liblapack-dev \
  libexpat1-dev \
  libsqlite3-dev \
  zlib1g-dev \
  gettext \
  patch \
  python-pip \
  libncurses5-dev \
  libreadline-dev \
  libdigest-perl-md5-perl \
  unzip \
  lcov \
  libboost-all-dev \
  qt4-qmake \
  qt4-dev-tools \
  lsb-release \
  libxml2-utils \
  python-lxml \
  python-psutil \
  vim \
  wget \
  rsync \
  libcurl4-openssl-dev \
  curl \
  bash-completion \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

ENV GOOGLETEST_VERSION 1.8.1

RUN cd /tmp \
&& wget https://github.com/google/googletest/archive/release-${GOOGLETEST_VERSION}.tar.gz \
&& tar -xzvf release-${GOOGLETEST_VERSION}.tar.gz \
&& cd googletest-release-${GOOGLETEST_VERSION} \
&& mkdir build \
&& cd build \
&& cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON .. \
&& make \
&& make install \
&& rm -f /tmp/release-${GOOGLETEST_VERSION}.tar.gz \
&& cd ~ \
&& rm -rf /tmp/googletest-release-${GOOGLETEST_VERSION}*

RUN ldconfig

RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" \
  && chmod +x /usr/local/bin/gosu

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN useradd -l -m -d /home/${USER} --user-group ${USER}

COPY install_dynawo.sh /opt

WORKDIR /home/${USER}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
