name: CI Nightly Jammy Image

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: |
          cd CI-nightly
          docker build . --file Dockerfile.jammy --tag dynawo/dynawo-ci-nightly-jammy:latest

      - name: Docker Push
        run: docker push dynawo/dynawo-ci-nightly-jammy
