name: Developers Debug Image

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 22 * * 1-5"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Clean space on device
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build the Docker image
        run: |
          cd Developers
          docker build . --file Dockerfile.debug --tag dynawo/dynawo-dev:debug

      - name: Docker Push
        run: docker push dynawo/dynawo-dev:debug
