name: Distribution gcc11 Image

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: |
          cd Distribution-gcc11
          docker build . --file Dockerfile --tag dynawo/dynawo-distribution-gcc11:latest

      - name: Docker Push
        run: docker push dynawo/dynawo-distribution-gcc11
